'use strict';
const {chromium}=require(process.env.DEXCUT_PLAYWRIGHT||'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const mov='/tmp/dexcut-gif-qa.mov';
cp.execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-f','lavfi','-i','testsrc2=size=320x240:rate=10','-t','3','-c:v','mpeg4','-q:v','5','-an',mov],{timeout:30000});
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(p,(err,data)=>{if(err){res.writeHead(404).end();return}const ext=path.extname(p);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.mov':'video/quicktime','.mp4':'video/mp4','.webp':'image/webp','.png':'image/png','.json':'application/json'})[ext]||'application/octet-stream'});res.end(data)})});
(async()=>{await new Promise(ok=>server.listen(0,'127.0.0.1',ok));let browser;try{
browser=await chromium.launch({headless:true,executablePath:process.env.DEXCUT_BROWSER||undefined,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:390,height:844},acceptDownloads:true});
const faults=[];page.on('pageerror',e=>faults.push(e.message));
await page.goto('http://127.0.0.1:'+server.address().port+'/');
await page.locator('#fileInput').setInputFiles(mov);
await page.locator('[data-job="gif"]').click();
await page.locator('#fields [data-key="start"]').fill('999');
await page.locator('#sheetRun').click();
await page.locator('#sheetResult').waitFor({state:'visible',timeout:120000});
assert(await page.locator('#sheetResultActions [data-action="share"]').isHidden());
assert(await page.locator('#sheetResultActions [data-action="save"]').isHidden());
assert(await page.locator('#sheetResultActions [data-action="use-result"]').isHidden());
assert(await page.locator('#sheetResultActions [data-action="retry"]').isVisible());
assert(await page.locator('#copyError').isVisible());
assert(await page.locator('#sheetPreview').isHidden());
assert(await page.locator('#resultHub').isHidden());
assert((await page.locator('#errorBox').innerText()).includes('selection'));
await page.locator('#sheetResultActions [data-action="retry"]').click();
assert(await page.locator('#configPane').isVisible());
await page.locator('#fields [data-key="start"]').fill('0');
await page.locator('#fields [data-key="length"]').fill('2');
await page.locator('#sheetRun').click();
await page.waitForFunction(()=>!document.querySelector('#sheetResult')?.classList.contains('hidden') && document.querySelector('#sheetResultTitle')?.textContent==='Ready to play',null,{timeout:120000});
assert(await page.locator('#errorBox').isHidden());
assert(await page.locator('#sheetResultActions [data-action="save"]').isVisible());
const download=page.waitForEvent('download',{timeout:15000});
await page.locator('#sheetResultActions [data-action="save"]').click();
const saved=await download;const file=await saved.path();const bytes=fs.readFileSync(file);
assert(bytes.length>1000);
assert(bytes.subarray(0,6).toString('ascii').startsWith('GIF8'));
assert.equal(faults.length,0,JSON.stringify(faults));
console.log(JSON.stringify({result:'PASS',container:'QuickTime .mov',invalidRange:'rejected',retry:'successful',bytes:bytes.length,gifHeader:bytes.subarray(0,6).toString('ascii'),jsErrors:faults.length}));
}finally{await browser?.close();server.close()}})().catch(e=>{console.error('GIF_QA_FAIL',e.stack||e);server.close();process.exitCode=1});
